### ISSUE TITLE
10.1 release is actually 10.0.1

### ISSUE THREAD

**Issue by alandtse** [CERTCC/kaiju#12]
**Describe the bug**

The released 10.1 release appears to be built for 10.0.1. If trying to add to Ghidra 10.1, it reports an incompatible version error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sei-eschwartz** [comment]
Sorry about the delay on this.  The problem is that the 10.1 "release" was actually from a typo.  I just opened a PR to build for 10.1 and 10.1.1 in #14.  Assuming it works ok, I'll merge it soon.
