### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pantrombka** [CERTCC/kaiju#13]
I'm trying build kaiju for ghidra 10.0.4. 
Unfortunately without success

* What went wrong:
Execution failed for task ':buildExtension'.
> Could not add file 'C:\kaiju\buildSrc\.gradle\7.3.3\executionHistory\executionHistory.lock' to ZIP 'C:\kaiju\dist\ghidra_10.0.4_PUBLIC_20211228_kaiju.zip'.

**Comment by sei-gwassermann** [comment]
Looks like you got a lock file, which usually means that gradle has crashed or had some sort of issue. You can manually delete all the `.lock` files and try to run gradle again.

**Comment by sei-eschwartz** [comment]
Looks like this is resolved so I'm closing it.
