### ISSUE TITLE
Z3 not found, even when Z3 and jars are installed

### ISSUE THREAD

**Issue by srobertjames** [CERTCC/kaiju#20]
**Describe the bug**
GhiHorn shows: "Warning, Z3 libraries not found, GhiHorn will not run"

Note: The error message is unclear if GhiHorn can't find the z3 jar, _or_ the z3 jar can't find the local libs.

Yet Z3 is installed and seems to work:
```
~/.ghidra/.ghidra_10.1.1_PUBLIC/Extensions/kaiju/lib$ ls
com.microsoft.z3.jar  gson-2.8.6.jar  jopt-simple-5.0.4.jar  kaiju.jar  kaiju-src.zip  README.txt

~/.ghidra/.ghidra_10.1.1_PUBLIC/Extensions/kaiju/lib$ z3 -version
Z3 version 4.8.14 - 64 bit

~$ ldconfig -p | grep z3
	libz3java.so (libc6,x86-64) => /usr/local/lib/libz3java.so
	libz3.so (libc6,x86-64) => /usr/local/lib/libz3.so

~$ lsb_release -r
Release:	21.04

~$ uname -a
Linux 5.11.0-46-generic #51-Ubuntu SMP Thu Jan 6 22:14:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

~$ ls /usr/local/lib/ | grep z3
com.microsoft.z3.jar
libz3.a
libz3java.so
libz3.so
```
Java Jar is present in both the Kaiju dir and elsewhere.
**To Reproduce**
1. Install z3 to Ubuntu 
2. Install Kaiju to Ghidra
3. Run GhiHorn

**Expected behavior**
GhiHorn should run, but gives the above error that it can't find Z3

**Additional context**
I read about GhiHorn and am very excited to try it.  I've used Z3 successfully before (though not from Java).  However, GhiHorn can't seem to find the required libs.

This may not be a GhiHorn issue, but simply a Java / z3 issue.  I have no means of testing Java z3.  The example at https://stackoverflow.com/questions/60403775/how-to-setup-a-java-development-environment-for-z3 seems to be out of date with my Java compiler:

```
/tmp$ javac -version
javac 17.0.1
/tmp$ javac -cp /usr/local/lib/com.microsoft.z3.jar JavaExample.java 
JavaExample.java:611: error: incompatible types: Expr<Sort> cannot be converted to IntExpr
            xs[j] = (IntExpr) ctx.mkConst(names[j], types[j]);
                                         ^
JavaExample.java:612: error: incompatible types: Expr<Sort> cannot be converted to IntExpr
            vars[j] = (IntExpr) ctx.mkBound(2 - j, types[j]); // <-- vars
                                           ^
JavaExample.java:1402: error: incompatible types: Expr<Sort> cannot be converted to BitVecExpr
        BitVecExpr x = (BitVecExpr) ctx.mkConst("x", bv_type);
                                               ^
JavaExample.java:1403: error: incompatible types: Expr<Sort> cannot be converted to BitVecNum
        BitVecNum zero = (BitVecNum) ctx.mkNumeral("0", bv_type);
                                                  ^
JavaExample.java:1427: error: incompatible types: Expr<Sort> cannot be converted to BitVecNum
        BitVecExpr c103 = (BitVecNum) ctx.mkNumeral("103", bv_type);
                                                   ^
Note: JavaExample.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
```

**Comment by sei-gwassermann** [comment]
Thank you for the report @srobertjames! We are thinking hard about how to best streamline this for all platforms in the future so thanks for patience with getting Z3 installed manually in the meantime.

My guess is that `/usr/local/lib` is probably not on your PATH, so the system can't find and load the libraries once Java goes looking for them.

In our automated build process it looks like the `LD_LIBRARY_PATH` variable is set. Do you have that? If not, try to set it first with something like:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/`

I haven't tried this out yet so if it doesn't work please let me know. I'll have an Ubuntu system on hand to try to troubleshoot this!

**Comment by srobertjames** [comment]
> My guess is that `/usr/local/lib` is probably not on your PATH, so the system can't find and load the libraries once Java goes looking for them.

**Confirmed**: `/usr/local/lib` is not in my `PATH`

> In our automated build process it looks like the `LD_LIBRARY_PATH` variable is set. Do you have that? If not, try to set it first with something like: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/`

The envar `LD_LIBRARY_PATH` is not set at all.  Can you clarify: Should I add `/usr/local/lib` to `PATH` or to `LD_LIBRARY_PATH`? And, once I do that, do I all need to do is invoke ghidra with those variables, or do I somehow need to configure or rebuild kaiju?

**Comment by sei-gwassermann** [comment]
One way to resolve this is to include the path to your Z3 libraries/binaries as a parameter to the Java VM, which you can do by adding the following to the `ghidraRun` (or `ghidraRun.bat` on Windows) file:
```
-Djava.library.path=/path/to/z3/lib
```

This goes in the empty quotes, which is the Ghidra supported way of passing parameters to Java. So you'll end up with a line that looks something like (in Linux, for example):
```
# Launch Ghidra
"${SCRIPT_DIR}"/support/launch.sh bg Ghidra "${MAXMEM}" "-Djava.library.path=/path/to/Ghidra/Extensions/kaiju/os/linux_x86_64" ghidra.GhidraRun "$@"
```

Updating instructions for this in the updated release coming soon.
