### ISSUE TITLE
GhiHorn error analyzing ARM binary

### ISSUE THREAD

**Issue by kiranravindran90** [CERTCC/kaiju#21]
I installed GhiHorn in Windows as per the below instructions (skipped step 2).
________________________________________________________________________________________________
Installation
1. You need to install Z3 and the Z3 java bindings
        a. You need to add the jar file (com.microsoft.z3.jar) to the GhiHorn/lib directory to make it available in the plugin.
            On Windows, you can place this .jar file in the same directory as ghidraRun.bat
        b. You need to put the z3 and java binding libraries in a location that is available
            On MacOS these files are libz3.dylib and libz3java.dylib
            On linux these files are: libz3.so and libz3java.so
            On Windows, these files are libz3.dll and libz3java.dll
2. Build the GhiHorn plugin. The plugin build process uses gradle with some addtions:
        a. Run gradle to build the plugin
        b. Run gradle install to build the distribution package and copy it to Ghidra
            Be sure to set your GHIDRA_INSTALL_DIR to your ghidra installation in the file gradle.properties before attempting to build.
3. Following step 2, the plugin should be installed. You may need to restart Ghidra to make the plugin available.
4. You can launch the plugin by pressing CTRL-G or selecting GhiHorn from the CERT menu.
__________________________________________________________________________________________________________

For the Step 1-b, I added libz3.dll & libz3java.dll in the same path as ghidraRun.bat.
And I skipped Step 2.

But I can see GhiHorn in the CERT menu & able to run Path analyzer. It returned "null" everytime.
Not sure if GhiHorn wasnt properly built (as i skipped step 2) or its something else.

**Comment by sei-gwassermann** [comment]
We unfortunately haven't tested this much on Windows yet to my understanding, thank you for your patience! It may be necessary to compile for Windows to make sure it works with windows dlls, but I am not sure.

@sei-jgennari do you have any thoughts?

**Comment by kiranravindran90** [comment]
Just to add (see img below).
The status looks fine when i open GhiHorn. Curious if it will work as expected as I skipped Step 2 (building using gradle).
![image](https://user-images.githubusercontent.com/90866692/159847565-ca37bf49-3682-4081-88d7-f942cd894115.png)

**Comment by jeffgennari** [comment]
One thing that may help with trouble shooting here is to check Ghidra's application log. On Linux/OS X systems this is in your home directory > .ghidra/.ghidra_VERSION/application.log. It is probably in a similar place on Windows. All exceptions will be logged there. You may be able to get more information on what is going wrong from that file.

**Comment by sei-gwassermann** [comment]
Thanks for this! It definitely looks to me like there's a problem with the Decompiler, and then Ghihorn is failing because it isn't getting the decompiler output it expects. This could possibly be a change in how the Decompiler API works, but I would say that's unlikely. What version of Ghidra are you using? Otherwise, it might be a bug in Ghidra, or something interesting/weird about the binary you are analyzing that is confusing ghidra (and we should do better error/exception handling for in Ghihorn/Kaiu).

**Comment by kiranravindran90** [comment]
I am using "Ghidra_10.1.2_PUBLIC_20220125".
The Binary I am using is a ARM Cortex 64-bit (A76) Binary. But I couldn't only find that combination, so tried ARM V8T.
The decompiled code has lot of warnings -
"WARNING: Control flow encountered bad instruction data"
"WARNING: Bad instruction - Truncating control flow here"
"WARNING: Control flow encountered bad instruction data"
"WARNING: This function may have set the stack pointer"
"WARNING: Globals starting with '_' overlap smaller symbols at the same address"

So kind of unsure if its due to the input Binary type or a bug.

**Comment by sei-gwassermann** [comment]
This seems like a very similar error to the one in #23. I have a patch coming that should address the error message. The error seems to be coming from Ghidra's High PCode somehow so will need some more investigation. I notice both this one and #23 are both running on ARM binaries and wonder if that is related.

**Comment by sei-eschwartz** [comment]
If this is still an issue, please upload a binary that triggers it and I'll look into it.
