### ISSUE TITLE
Error: Bit length must be >= 1 and <= 64

### ISSUE THREAD

**Issue by goo99x** [CERTCC/kaiju#24]
When running PathAnalyzer on a particular x86 binary (DLL with exports, imports, and post-OOAnalyzer), during function hornifcation an error occurs. It's not clear which function is causing this nor is it clear where this error message is coming from! I checked strings for Z3 and Kaiju, but couldnt find this error message. The search path is intraprocedural and the function has no external calls (another question is does the entire program need to be hornified or can only a subset of functions?).

- Ghidra 10.1.3
- Kaiju 10.1.3 release
- Z3 same as release's Z3 java jar (4.8.14.0)
- System: Ubuntu 22.04

I'm not sure reproducing this without additional logging (such as per function debug prints) or the binary itself will be possible, but I'm available to give more information if needed.

**Comment by sei-eschwartz** [comment]
The error is coming from here: 

https://github.com/NationalSecurityAgency/ghidra/blob/534fd5253a8106bb27188bbadf115e999fe2b9a7/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/scalar/Scalar.java#L62

@sei-jgennari is the right person to ask about this, but unfortunately he's not available right now.

Are you able to share the binary?

**Comment by goo99x** [comment]
Surprisingly, I can. [DataLibrary.zip](https://github.com/CERTCC/kaiju/files/9213815/DataLibrary.zip)

**Comment by jeffgennari** [comment]
@sei-eschwartz  is correct, this is a limitation of the Ghidra Scalar type

**Comment by jeffgennari** [comment]
> 

Just to follow up, the class `ghidra.program.model.pcode.HighConstant` is backed by`ghidra.program.model.scalar.Scalar`, which itself just wraps a long value (64b max). Certain p-code don't really adhere to this limitation, for example from your binary: `(unique, 0x1000039a, 16) INT_AND (register, 0x1240, 16) , (const, 0x8000000000000000, 16)` the first input varnode is too large to represent, but it is still assigned a HighConstant. This leads to an exception

**Comment by goo99x** [comment]
> > 
> 
> Just to follow up, the class `ghidra.program.model.pcode.HighConstant` is backed by`ghidra.program.model.scalar.Scalar`, which itself just wraps a long value (64b max). Certain p-code don't really adhere to this limitation, for example from your binary: `(unique, 0x1000039a, 16) INT_AND (register, 0x1240, 16) , (const, 0x8000000000000000, 16)` the first input varnode is too large to represent, but it is still assigned a HighConstant. This leads to an exception

Nice find. Which instruction/function is generating this p-code? 
If Ghidra itself has this limitation, is this bug triggered during normal decompilation? If so, I'll open an issue upstream. If not, maybe there is a workaround?
Can Kaiju catch exceptions like this and instead of bailing out of the entire tool execution, fail the function and move on?

**Comment by goo99x** [comment]
It seems that this pcode is being generated as a result of XMM related instructions. While the operation is happening on more than 8 bytes at a time,  `0x8000000000000000` can still be represented as a 64-bit value. HighConstant isnt backed by Scalar directly, but by a `long` in the underlying Varnode. It is cast to a scalar using `getScalar`, which takes into account the size of the underlying varnode (16), leading to the exception. Ghidra's API is confusing here - if it can only store 64-bits in the varnode backed long, why does it let the bitsize of the scalar exceed that?

**Comment by jeffgennari** [comment]
I believe the specific instruction that is generating the p-code in question: (`(unique, 0x1000039a, 16) INT_AND (register, 0x1240, 16) , (const, 0x8000000000000000, 16)`) is at address 100d33a4:  `AND        EAX,0x8000`

**Comment by sei-eschwartz** [comment]
> Ghidra's API is confusing here - if it can only store 64-bits in the varnode backed long, why does it let the bitsize of the scalar exceed that?

I agree.  Is the bitfield in the High Pcode even correct, or is it truncated?

**Comment by sei-eschwartz** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/4510

**Comment by sei-gwassermann** [comment]
I merged in a hotfix that will at least catch the exception for now, until the issue gets a proper fix upstream. It is now available in the latest release. thanks for reporting!

**Comment by sei-gwassermann** [comment]
This issue should be resolved now as the upstream fix appears to have been included in Ghidra 10.2. I've fixed up our build process so there's now prebuilt Kaiju extensions for Ghidra 10.2. Recommended anyone else facing this issue to update Ghidra and Kaiju! Please file a new ticket if encounter any new bugs.
