### ISSUE TITLE
Consider reworking GitHub releases

### ISSUE THREAD

**Issue by somebody1234** [CERTCC/kaiju#28]
**Is your feature request related to a problem? Please describe.**
Hey, I maintain (well, "maintain") the [Arch Linux AUR package for this extension](https://aur.archlinux.org/packages/ghidra-extension-kaiju-bin) - however because of how the releases currently happen, there seem to be a couple of minor issues:
- Builds happen every week, regardless of whether anything has been changed
- Old releases are deleted, so to make the package keep working it must be updated every week

**Describe the solution you'd like**
Depends what would be a good solution, I guess... you could probably, say, make the pipelines manually triggered instead

**Comment by sei-eschwartz** [comment]
Thanks for letting us know that this is causing you some issues.  We'll see if we can do something a bit more sensible in pipelines.  (We are building every week to build and test against ghidra git master, but obviously the normal Ghidra versions don't need to rebuilt weekly...)

**Comment by sei-eschwartz** [comment]
I changed the Pipelines to build every week, but not push a new release each week.  Since we don't have really releases, this will build every time we push to main, which is probably what we want.
