### ISSUE TITLE
How to get GhiHorn to find Z3 dylibs in macOS

### ISSUE THREAD

**Issue by YSaxon** [CERTCC/kaiju#30]
I just wanted to leave this tip for anyone else who encounters the same problem I struggled with for quite a while.

If you are on macOS and are continually getting errors like
```Warning: Z3 libraries not found, GhiHorn will not run```
and
```java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native```

try the following solution
https://github.com/Z3Prover/z3/issues/294#issuecomment-352472522

TLDR: instead of using env vars to specify the location of the dylib files, just move or link the dylibs to where they will be looked for.
```
ln -s libz3.dylib /usr/local/lib
sudo ln -s libz3java.dylib  /Library/Java/Extensions
```

**Comment by sei-gwassermann** [comment]
Thank you for this comment. Your suggestion is one option that works, by placing the libraries in a standard system location. The Java VM can also be launched by editing your `ghidraRun` script to add additional locations to search when Ghidra boots up. See #20 for more info. I am not sure how to make this change programmatically, but can be done manually by adding to the empty quotes in the `ghidraRun` script:
```
-Djava.library.path=/path/to/z3/lib
```
