### ISSUE TITLE
Cannot invoke method java.time...

### ISSUE THREAD

**Issue by pantrombka** [CERTCC/kaiju#34]
Cannot invoke "java.time.temporal.Temporal.until(java.time.temporal.Temporal, java.time.temporal.TemporalUnit)" because "startInclusive" is null
java.lang.NullPointerException: Cannot invoke "java.time.temporal.Temporal.until(java.time.temporal.Temporal, java.time.temporal.TemporalUnit)" because "startInclusive" is null
	at java.base/java.time.Duration.between(Duration.java:490)
	at kaiju.tools.ghihorn.GhiHornProvider.endAnalysis(GhiHornProvider.java:674)

**Comment by sei-gwassermann** [comment]
Thanks for the report @pantrombka ! can you provide any further details about how this error came about? does it only happen with one particular program or many?

**Comment by sei-gwassermann** [comment]
I added a simple check for null in the next release which should prevent an error but the duration won't be accurate. Will need more info to try to figure out what's going on and properly fix it.
