### ISSUE TITLE
[Bug] Could not complete analysis: Failed to generate variables for p-code

### ISSUE THREAD

**Issue by widberg** [CERTCC/kaiju#38]
Unfortunately I encounter some version of this message with every binary I try using the GhiHorn PathAnalyser on. Is there a way around this? Is this a problem with Ghidra or Kaiju?

```plaintext
Could not complete analysis: Failed to generate variables for p-code: (register, 0x1106, 10) INDIRECT (const, 0x0, 10) 
, (const, 0xd3, 4). This is an issue with Ghidra's HighConstant class
---------------------------------------------------
Build Date: 2023-Feb-08 1242 EST
Ghidra Version: 10.2.3
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Private Build 17.0.6
OS: Linux 5.19.0-38-generic amd64
```

Kaiju: 230331
Ghidra: 10.2.3

**Comment by sei-gwassermann** [comment]
I believe this is an upstream issue with Ghidra, but I'll check with @sei-jgennari about it. Do you have more information about what binaries you are looking at? For example, I believe the error occurs often with ARM executables. Thanks for the report!

**Comment by sei-jgennari** [comment]
@widberg do you have any additional information about the programs that you are analyzing? What is the architecture?

**Comment by widberg** [comment]
Here is a minimal reproducible example. The problem appears to be related to statically linking with GLIBC. When I dynamically link the binaries I get different errors.

Statically linked X86_32 binary compiled on Ubuntu 22.04.2 64-bit with gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 and Ubuntu GLIBC 2.35-0ubuntu3.1 using the following source file and command.

```c
// main.c
int main () {
}
```

```sh
gcc -m32 -g -O0 -Wall -Wextra -Werror -pedantic -static main.c
```

Using the program entry point as the start address and the end of main as the end address I get the error.

**Comment by edmcman** [comment]
We should really print the exception here, and maybe the address of the Pcode operator: https://sourcegraph.com/github.com/CERTCC/kaiju/-/blob/src/main/java/kaiju/tools/ghihorn/hornifer/horn/expression/PcodeExpression.java?L56

**Comment by sei-gwassermann** [comment]
Just created a new 230406 release that includes better printing of exception data that might help figure out what's going on here.

**Comment by edmcman** [comment]
[main.zip](https://github.com/CERTCC/kaiju/files/11172950/main.zip)

**Comment by sir-maniac** [comment]
I think I ran into a similar issue.  Was able to use debug and tracked down this issue [here](
https://github.com/NationalSecurityAgency/ghidra/blob/eec0a1d5ff7630d4d4c26e11f22451971702f5c5/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/HighConstant.java#L85).  

It seems there are [HighConstant](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/HighConstant.java) values that can't fit within the 64-bit `Scalar` and so it throws an exception.

I was able to fix this by modifying [HornVariable](https://github.com/CERTCC/kaiju/blob/main/src/main/java/kaiju/tools/ghihorn/hornifer/horn/variable/HornVariable.java) to check the size. Like so:

```diff
@@ -154,8 +154,10 @@ public class HornVariable implements HornExpression {
 
         if (highVariable instanceof HighConstant) {
             HighConstant hc = (HighConstant) highVariable;
-            Long value = hc.getScalar().getValue();
-            return new HornConstant(value);
+            if (hc.getSize() <= 8) {
+               Long value = hc.getScalar().getValue();
+               return new HornConstant(value);
+            }
         }
 
         return new HornVariable(highVariable);
```

Seemed to work fine after that.

**Comment by sei-eschwartz** [comment]
That will just throw away the constant if it is too large to fit into a scalar.  This is really a problem that needs to be fixed on Ghidra's end, unfortunately.

I had an issue opened, but they closed it with a band-aid fix: https://github.com/NationalSecurityAgency/ghidra/issues/4510
