### ISSUE TITLE
[Bug] PathAnalyzer entryBlock is null error

### ISSUE THREAD

**Issue by psparc82** [CERTCC/kaiju#40]
**Describe the bug**
The PathAnalyzer is unable to produce any outputs due to: `Error: Cannot invoke "kaiju.tools.ghihorn.hornifer.block.HornBlock.getStartAddress()" because "entryBlock" is null` even in very basic example applications.

**To Reproduce**
1. Compile a basic C program...
`int main(int argc, char **argv) { return argc * 2; }`
`gcc -O0 program.c -o program`
3. Analyze `program` in Ghidra
4. Open GhiHorn and attempt path analysis from the `main` function to any location after `main`
5. The following error is logged in the Status window:
![image](https://user-images.githubusercontent.com/131255834/233046909-a2770af8-7a2e-4c58-a4e6-e86846a0db54.png)
6. No results are output

**Potential Issue**

I think issue has to do with `HornFunctionInstance.java:107` where the `entryBlock` is returned (but is null) then line 108 dereferences the null value (trying to get the startAddress)

**...OR...**

its an issue with a slight version mismatch between the latest Ghidra available to download (` ghidra_10.2.3_PUBLIC_20230208.zip`) vs the Ghidra version the plugin seems to be built for (`ghidra_10.2.3_PUBLIC_20230406`). I can't find Ghidra `ghidra_10.2.3_PUBLIC_20230406.zip` anywhere to download (which is in the Kaiju Ghidra plugin filename).

I've built Ghidra from source for the date 20230406 (to try to version match Kaiju) and I've built Kaiju from source but still get this error

**Versions**
1. Ubuntu: 22.04.2
2. GCC: 11.3.0
3. Ghidra: ghidra_10.2.3_PUBLIC_20230208.zip
4. Kaiju Ghidra plugin: ghidra_10.2.3_PUBLIC_20230406_kaiju.zip 
5. z3: 4.12.2 - 64 bit

**Comment by sei-gwassermann** [comment]
It might have been something that changed in Ghidra 10.2 compared to 10.1. The unit tests pass so interesting that the tests are not catching this. I see this same behavior loading up different executables, sometimes Ghidra fails to find an entry point, but sometimes it works just fine. I'm not sure what the common link is just yet.
