### ISSUE TITLE
"Warning: NoClassDefFoundError while loading Z3." using Ghidra 10.3 + Kaiju 20230519 on Windows.

### ISSUE THREAD

**Issue by AdmiralCurtiss** [CERTCC/kaiju#44]
**Describe the bug**
Status check reports that it can't load the Z3 libraries. Fn2Hash is unavailable in the CodeBrowser, which I believe is caused by this.

**To Reproduce**
1. Download https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.3_build
2. Download https://github.com/CERTCC/kaiju/releases/tag/230518
3. Download https://jdk.java.net/java-se-ri/17 (or another JDK, I also tried Oracle's current 17 release as well as OpenJDK 20 and had the same problem with each).
4. Extract Ghidra and JDK somewhere, extract Kaiju to [ghidradir]/Ghidra/Extensions/.
5. Launch Ghidra and point it at the JDK.
6. Accept the Ghidra terms.
7. Once Ghidra launches the Kaiju Status Check will pop up with the error. If it doesn't, go to File -> Configure, check CERT Kaiju if it's unchecked, then go to Kaiju -> Status Check.

**Expected behavior**
I would expect there to be no error using the distribution in the Github Releases, as it definitely ships with some Z3 libraries.

**Screenshots**
![image](https://github.com/CERTCC/kaiju/assets/4522237/297f3e1c-0768-4268-a95c-a86a89e6ed97)
![image](https://github.com/CERTCC/kaiju/assets/4522237/aa2c8af6-4031-4710-b5b7-439d131e27e6)
![image](https://github.com/CERTCC/kaiju/assets/4522237/8365fdee-0717-4423-956a-18c950cdbf7d)

**Desktop (please complete the following information):**
 - Windows 10 Pro 22H2
 - Ghidra Version 10.3
 - Kaiju Version 230518

**Additional context**
I would have hoped that there would be some clue about the exception in the Ghidra log, but I'm not seeing anything unfortunately. 

---

If I run the headless analyzer via command line instead it *seems* to be working fine, or at least it's not showing the exception.

```
..\..\..\support\analyzeHeadless.bat" /tmp tmpKaijuHeadlessProj -okToDelete -deleteProject -import c:\__\dgs_patch_exe.exe -preScript KaijuSetupScript.java -postScript KaijuExportCSVHeadless.java C:\__\dgs_patch_exe.FnHashes.csv
```

I get an output, at least, though I can't verify whether it would be different without the error in the GUI.

I also see hashes in Window -> CERT Function Hash Viewer, but again I'm not sure where these actually come from since it doesn't allow me to run the analysis manually.

![image](https://github.com/CERTCC/kaiju/assets/4522237/75ea1885-8e75-493c-aab5-c2074b38fd8e)

Anyway, I'm mostly confused here, because it seems to be working *somewhat* but clearly not entirely; is there anything I can do to diagnose this further?

**Comment by sei-eschwartz** [comment]
I think this should be working now
