### ISSUE TITLE
DisasmImprovementsAnalysis step extremely slow

### ISSUE THREAD

**Issue by MattMills** [CERTCC/kaiju#65]
**Describe the bug**
Using Ghidra 11 and the latest version of Cert Kaiju I was trying to run headless auto analysis of a bunch of executables and it stalled out on the first 32 bit executable running Kaiju's DisasmImprovements. Executable is 14 MB and I let it run for 9 hours before giving killing it and disabling that auto analysis step.

The log  is largely composed of these two messages with different addresses:
```
2023-12-30 20:15:10 DEBUG (X86ImproverStrategy) Created instructions at: [[00a7cf28, 00a7cf2a] ]  
2023-12-30 20:15:12 DEBUG (X86ImproverStrategy) Created instructions at: [[00a7cfab, 00a7cfad] ]  
2023-12-30 20:15:12 DEBUG (X86ImproverStrategy) Created alignment at: [00a7cffd, 00a7cfff]  
2023-12-30 20:15:12 DEBUG (X86ImproverStrategy) Created alignment at: [00a7d02e, 00a7d02f]  
```

Executable I was analyzing is attached (in a zip):
[definitelynotstellaris_1.3.0.exe.zip](https://github.com/CERTCC/kaiju/files/13800121/definitelynotstellaris_1.3.0.exe.zip)

Running analysis with Disasm Improvements disabled completes in 12 minutes

```
INFO  Fn2Hash analysis complete: Found hashes for 72344 functions. (FnHashAnalyzer)  
INFO  -----------------------------------------------------
    ASCII Strings                              1.327 secs
    Apply Data Archives                        0.807 secs
    Call Convention ID                         1.469 secs
    Call-Fixup Installer                       2.909 secs
    Create Address Tables                      0.031 secs
    Create Address Tables - One Time           5.729 secs
    Create Function                           12.876 secs
    Data Reference                             6.751 secs
    Decompiler Switch Analysis               129.277 secs
    Demangler Microsoft                        1.025 secs
    Disassemble                               38.140 secs
    Disassemble Entry Points                   2.076 secs
    Disassemble Entry Points - One Time        0.038 secs
    Embedded Media                             0.120 secs
    External Entry References                  0.004 secs
    Function ID                               21.855 secs
    Function Start Pre Search                  0.105 secs
    Function Start Search                     16.280 secs
    Function Start Search After Code           5.734 secs
    Function Start Search After Data           3.724 secs
    Function Start Search delayed - One Time   0.000 secs
    Kaiju Function Hashing                   130.078 secs
    Non-Returning Functions - Discovered      38.514 secs
    Non-Returning Functions - Known            0.009 secs
    PDB MSDIA                                  0.006 secs
    Reference                                  9.038 secs
    Scalar Operand References                 27.109 secs
    Shared Return Calls                        8.639 secs
    Stack                                    109.708 secs
    Subroutine References                      4.381 secs
    Subroutine References - One Time           0.075 secs
    Windows x86 PE Exception Handling         18.702 secs
    Windows x86 PE RTTI Analyzer               0.684 secs
    Windows x86 Thread Environment Block (TEB) Analyzer     0.018 secs
    WindowsResourceReference                   1.375 secs
    X86 Function Callee Purge                  3.729 secs
    x86 Constant Reference Analyzer          108.891 secs
-----------------------------------------------------
     Total Time   711 secs
-----------------------------------------------------
 (AutoAnalysisManager)  
 ```

**To Reproduce**
1. Auto analyze 32 bit executable

**Expected behavior**
This seems extremely excessive runtime for default enabled behavior

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by sei-eschwartz** [comment]
Thanks for sharing this, we'll take a look at what is going on.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Matt Mills ***@***.***>
Sent: Saturday, December 30, 2023 10:43:27 PM
To: CERTCC/kaiju ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CERTCC/kaiju] DisasmImprovementsAnalysis step extremely slow (Issue #65)

Warning: External Sender - do not click links or open attachments unless you recognize the sender and know the content is safe.


Describe the bug
Using Ghidra 11 and the latest version of Cert Kaiju I was trying to run headless auto analysis of a bunch of executables and it stalled out on the first 32 bit executable running Kaiju's DisasmImprovements. Executable is 14 MB and I let it run for 9 hours before giving killing it and disabling that auto analysis step.

The log is largely composed of these two messages with different addresses:

2023-12-30 20:15:10 DEBUG (X86ImproverStrategy) Created instructions at: [[00a7cf28, 00a7cf2a] ]
2023-12-30 20:15:12 DEBUG (X86ImproverStrategy) Created instructions at: [[00a7cfab, 00a7cfad] ]
2023-12-30 20:15:12 DEBUG (X86ImproverStrategy) Created alignment at: [00a7cffd, 00a7cfff]
2023-12-30 20:15:12 DEBUG (X86ImproverStrategy) Created alignment at: [00a7d02e, 00a7d02f]


Executable I was analyzing is attached (in a zip):
definitelynotstellaris_1.3.0.exe.zip<https://github.com/CERTCC/kaiju/files/13800121/definitelynotstellaris_1.3.0.exe.zip>

Running analysis with Disasm Improvements disabled completes in 12 minutes

INFO  Fn2Hash analysis complete: Found hashes for 72344 functions. (FnHashAnalyzer)
INFO  -----------------------------------------------------
    ASCII Strings                              1.327 secs
    Apply Data Archives                        0.807 secs
    Call Convention ID                         1.469 secs
    Call-Fixup Installer                       2.909 secs
    Create Address Tables                      0.031 secs
    Create Address Tables - One Time           5.729 secs
    Create Function                           12.876 secs
    Data Reference                             6.751 secs
    Decompiler Switch Analysis               129.277 secs
    Demangler Microsoft                        1.025 secs
    Disassemble                               38.140 secs
    Disassemble Entry Points                   2.076 secs
    Disassemble Entry Points - One Time        0.038 secs
    Embedded Media                             0.120 secs
    External Entry References                  0.004 secs
    Function ID                               21.855 secs
    Function Start Pre Search                  0.105 secs
    Function Start Search                     16.280 secs
    Function Start Search After Code           5.734 secs
    Function Start Search After Data           3.724 secs
    Function Start Search delayed - One Time   0.000 secs
    Kaiju Function Hashing                   130.078 secs
    Non-Returning Functions - Discovered      38.514 secs
    Non-Returning Functions - Known            0.009 secs
    PDB MSDIA                                  0.006 secs
    Reference                                  9.038 secs
    Scalar Operand References                 27.109 secs
    Shared Return Calls                        8.639 secs
    Stack                                    109.708 secs
    Subroutine References                      4.381 secs
    Subroutine References - One Time           0.075 secs
    Windows x86 PE Exception Handling         18.702 secs
    Windows x86 PE RTTI Analyzer               0.684 secs
    Windows x86 Thread Environment Block (TEB) Analyzer     0.018 secs
    WindowsResourceReference                   1.375 secs
    X86 Function Callee Purge                  3.729 secs
    x86 Constant Reference Analyzer          108.891 secs
-----------------------------------------------------
     Total Time   711 secs
-----------------------------------------------------
 (AutoAnalysisManager)


To Reproduce
Steps to reproduce the behavior:

  1.  Auto analyze 32 bit executable

Expected behavior
This seems extremely excessive runtime for default enabled behavior

Screenshots
N/A

Desktop (please complete the following information):

  *   OS: Ubuntu 22.04
  *   Browser N/A
  *   Version N/A

Smartphone (please complete the following information):
N/A

Additional context

**Comment by sei-eschwartz** [comment]
@MattMills Can you please capture a "cycle" in the `application.log` file and upload it?  I'm particularly interested in whether the iteration count from https://github.com/CERTCC/kaiju/blob/main/src/main/java/kaiju/tools/disasm/DisasmImprovementsAnalyzer.java#L198 is increasing.

**Comment by sei-eschwartz** [comment]
One of the problem addresses, 0xa7cfab, is a an instruction after a `noreturn` function call.  Specifically, it follows the call to 0x419ff0, which seems like an abort-the-program function that invokes Watson.

So my guess is that Kaiju marks the memory as an instruction, and then some Ghidra noreturn analysis decides the code will never be reached, and reverts the memory to non-code.

**Comment by sei-eschwartz** [comment]
I manually marked 0xa7cfab as code and re-ran the other analyzers, and they did not unmark it as code.  But I suspect that manually marking a region as code is treated differently than an analyzer deciding something is code.  Anyway, the log of the cyclic behavior would be very helpful for me to understand what is going on.

**Comment by MattMills** [comment]
[application.log-2023-12-30-1.log.gz](https://github.com/CERTCC/kaiju/files/13846786/application.log-2023-12-30-1.log.gz)
This is the entire log file, including both the terminated and then successful run (as well as some other runs, I was doing automated analysis of a bunch of versions), the failed run starts from near the top of the log at timestamp 2023-12-30 10:23:11  and ends at 2023-12-30 20:17:44.

**Comment by MattMills** [comment]
Also this analyze headless session was using `MAXMEM=32G` and `VMARG_LIST="-XX:ParallelGCThreads=8 -XX:CICompilerCount=8 "` on a `AMD Ryzen Threadripper 1950X 16-Core Processor` with 128 GB of ram.

**Comment by MattMills** [comment]
From that log if I grep out the alignment, instructions, and Skipping Address log lines, this is all that is left:

```
2023-12-30 10:31:26 DEBUG (DisasmImprovementsAnalyzer) stellaris.exe - .ProgramDB  
2023-12-30 10:31:29 DEBUG (DisasmImprovementsAnalyzer) Analyzing gaps (iteration 1)...  
2023-12-30 18:41:01 DEBUG (X86ImproverStrategy) Disassembly status at 0092ec6f was: Disassembler requires a start which is an undefined code unit  
2023-12-30 19:10:51 DEBUG (X86ImproverStrategy) Disassembly status at 0099ab19 was: Disassembler requires a start which is an undefined code unit  
```

**Comment by sei-eschwartz** [comment]
Thanks!  I misunderstood your original message.  I was thinking it was an infinite loop, but it just sounds like it's really slow.  (I definitely observed this!)

**Comment by sei-eschwartz** [comment]
Initially it looks like it's going very quickly, but eventually there are seconds in between each log message.

```
2023-12-30 19:01:32 DEBUG (X86ImproverStrategy) Created alignment at: [0097fdf1, 0097fdff]  
2023-12-30 19:01:35 DEBUG (X86ImproverStrategy) Created instructions at: [[0097fe99, 0097fe9b] ]  
2023-12-30 19:01:37 DEBUG (X86ImproverStrategy) Created instructions at: [[0097fec2, 0097fec4] ]  
2023-12-30 19:01:40 DEBUG (X86ImproverStrategy) Created instructions at: [[0097feeb, 0097feed] ]  
2023-12-30 19:01:40 DEBUG (X86ImproverStrategy) Created alignment at: [0097ff01, 0097ff0f]  
2023-12-30 19:01:40 DEBUG (X86ImproverStrategy) Created alignment at: [0097ff7d, 0097ff7f]  
2023-12-30 19:01:43 DEBUG (X86ImproverStrategy) Created instructions at: [[00980059, 0098005b] ]  
2023-12-30 19:01:46 DEBUG (X86ImproverStrategy) Created instructions at: [[00980082, 00980084] ]  
2023-12-30 19:01:46 DEBUG (X86ImproverStrategy) Created alignment at: [00980099, 0098009f]  
2023-12-30 19:01:49 DEBUG (X86ImproverStrategy) Created instructions at: [[0098013c, 0098013e] ]  
```

**Comment by MattMills** [comment]
Just wanted to confirm that analysis for me is down to 640 seconds with this patch, so seems fixed, thanks for the quick turnaround.

**Comment by sei-eschwartz** [comment]
Great, thanks for confirming Matt!  And thanks for the initial report.  Let us know if you run into any other troubles.  We’re trying to keep Kaiju in a well maintained and useful state.

Ed
