### ISSUE TITLE
[PathAnalyzer] Error: Cannot invoke "String.length()" because "str" is null

### ISSUE THREAD

**Issue by F1o0T** [CERTCC/kaiju#67]
**Describe the bug**
I have executed the PathAnalyzer on a RISCV elf file, and I am getting this error message even though I am asking the extenstion to find the path between two addresses where no branches in between (Just to test it). 

**To Reproduce**
1. Load an elf
2. Open the code browser 
3. set a start address
4. set an end address that followes the start address with no branches in between. 
5. Clicked on Aalyze button 

**Expected behavior**
I was expecting to see tha path between the start and the end address. 

**Screenshots**
![image](https://github.com/CERTCC/kaiju/assets/32544388/f3239b75-c038-46e5-be83-7f61a4865ae6)

**Desktop (please complete the following information):**
 - OS: Same behviour on windows and Linux. 
 - Ghidra and GhiHorn extension version is 11.0.0

**Comment by F1o0T** [comment]
In additon, can you please share how can I debug the source code of this plugin in Eclipse using the GhidraDev eclipse plugin? 

Thanks in advance!

**Comment by F1o0T** [comment]
Here is the backtrace while debugging the error using eclipse with GhidraDev eclipse plugin. 

![image](https://github.com/CERTCC/kaiju/assets/32544388/8927ff51-e44c-4ed8-b269-333eca9a1740)

**Comment by sei-eschwartz** [comment]
@sei-jgennari This looks like it is in your code.  Any ideas where the null is coming from?

**Comment by edmcman** [comment]
I tried to figure it out from the backtrace, but failed.  @F1o0T if you could share a file that triggers this, it would be a big help.

I bet the problem is somewhere in here: https://github.com/CERTCC/kaiju/blob/c9b41a6819bec3220d0e1bf43ae4d38fb5a76773/src/main/java/kaiju/tools/ghihorn/hornifer/horn/variable/HornVariableName.java#L96

**Comment by sei-eschwartz** [comment]
Please upload a file that triggers this.  Thanks!
