### ISSUE TITLE
Every GUI option is missing

### ISSUE THREAD

**Issue by Anonymous941** [CERTCC/kaiju#82]
**Describe the bug**
While there are new options in the auto analyzer, there is no `Kaiju` tab and `CERT Function Hash Viewer` is not in the `Window` tab

**To Reproduce**
1. Go to `Window`
2. See error

**Expected behavior**
The options appearing

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: Ghidra 11.2 (NOT 11.2.1)

**Comment by sei-eschwartz** [comment]
Please carefully follow these instructions:

> Some functionality may require enabling Kaiju plugins. To do this, open the Code Browser then navigate to the menu File > Configure. In the window that pops up, click the Configure link below the "CERT Kaiju" category icon. A pop-up will display all available publicly released Kaiju plugins. Check any plugins you wish to activate, then hit OK. You will now have access to interactive plugin features.

If you think you did this, please take a screenshot of the list of plugins from the Configure link.  Here is mine.

![image](https://github.com/user-attachments/assets/458f1650-a5aa-42dc-b8de-cb953852e28e)

It is important to note that you must select `File > Configure` from the CodeBrowser tool, NOT the project manager.

**Comment by sei-eschwartz** [comment]
I am guessing you got this to work judging by #83

**Comment by Anonymous941** [comment]
> I am guessing you got this to work judging by #83

After I upgraded Ghidra, it prompted me with the plugin screen and I was able to select it.  But it probably would work on the older version if I open the plugin manager
