### ISSUE TITLE
GhiHorn PathAnalyzer "null" error when analyzing paths

### ISSUE THREAD

**Issue by ringzer0x00** [CERTCC/kaiju#9]
**Describe the bug**
Paths not showing on GhiHorn PathAnalyzer analysis

**To Reproduce**
Kaiju->GhiHorn
insert start/goal addresses->analyze

**Expected behavior**
Paths should appear or at least an explicative error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/65427334/141807161-d76faccb-217a-421f-88c6-47afa72f62aa.png)
**Desktop (please complete the following information):**
 - OS: Manjaro Linux
- Ghidra 10.0.4
- openjdk 11.0.13 2021-10-19

**Additional context**
GhiHorn was built from source. z3 is installed and working. I've run the tests provided in the autocats repo, which are all working.
If there's a possible way to have a log about what could be going wrong would be helpful to try and troubleshoot.

**Comment by ringzer0x00** [comment]
Update: I tried troubleshooting it on ghidraDebug and when running the analysis I get this:

DEBUG Exec Task GhiHornPlugin  (ToolTaskManager.java:302) 
java.lang.NullPointerException
	at kaiju.tools.ghihorn.hornifer.GhiHornifier.hornify(GhiHornifier.java:327)
	at kaiju.tools.ghihorn.GhiHornCommand.applyTo(GhiHornCommand.java:82)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:829)
INFO  Cancelled analysis  (GhiHornifier.java:145) 
ERROR GhiHornPlugin Failed: Error: null  (ToolTaskManager.java:460) 

Not sure if it can help, but it's the best error log I manager to get.

**Comment by ringzer0x00** [comment]
UPDATE: Tested the same analysis with a binary compiled on an Apple system (with gcc) and it did work.
Do binaries compiled on Linux require some special flags or are binaries for Linux based systems not supported by the framework?

**Comment by sei-gwassermann** [comment]
Thanks for this report! The first thought that comes to mind is to ask: did you run all of the Auto Analyzer tools before trying GhiHorn? The Error message above about not being able to invoke HighFunction.getFunction() sounds like it doesn't have the pcode which would be generated during analysis I think. If you're getting any errors during analysis, let us know. We have another report of the function hashing analyzer causing trouble here, so feel free to turn it off before running the analysis if necessary, the hashing doesn't affect ghihorn analysis results.

Thanks for testing on multiple systems too! We've definitely tested and used it on Linux. I don't believe there are any special flags or binaries required, so it might be more of an issue with Java finding the bindings library and/or the executable. @sei-jgennari might know more.

**Comment by ringzer0x00** [comment]
Hi, thanks for the fast response.
Yes, in both cases (actually both on Linux, the test binaries just came from different systems, the test environment was the same) I have run the auto-analyses and tried to run it without the CERT hashing functions and by excluding everything except the bare minimum in kaiju required to run GhiHorn.
I'd tend to exclude it's not working due to missing libraries and/or binaries because it does work for Apple binaries on the same system where Linux binaries give the aforementioned errors.

**Comment by sei-gwassermann** [comment]
I believe the previous pull requests plus some bugfix updates that are getting pushed later today resolve this issue so I will close it for now, but thank you for the report @ringzer0x00 and let us know if you have any further questions or issues!
