### ISSUE TITLE
Unable to find Z3 libraries and GhiHorn could not load (Apple Silicon)

### ISSUE THREAD

**Issue by localacct** [CERTCC/kaiju#90]
**Describe the bug**
Kaiju status check reported that Z3 libraries are not loaded and GhiHorn would not work. This is similar to #20 (https://github.com/CERTCC/kaiju/issues/20).

**To Reproduce**
1. Download the Kaiju package (https://github.com/certcc/kaiju/releases) for Ghidra 11.1.1
2. Download Ghidra 11.1.1
3. Install the extension using Ghidra GUI
4. Enable the extension using File > Configure inside Code Browser
5. Restart Ghidra

**Expected behavior**
GhiHorn should work, instead it shows that GhiHorn is missing Z3.

**Screenshots**
- I checked that Z3 is installed `Z3 version 4.13.3 - 64 bit`
- I checked that `com.microsoft.z3.jar` is located inside `"~/Library/ghidra/ghidra_11.1.1_PUBLIC/Extensions/kaiju/lib"`
- I manually copied `libz3.dylib`, `libz3java.dylib`and `libz3.a` to `/usr/local/lib`
- I modified ghidraRun to use the following line
`
"${SCRIPT_DIR}"/support/launch.sh bg jdk Ghidra "${MAXMEM}" "-Djava.library.path=/usr/local/lib" ghidra.GhidraRun "$@"
`
- When I relaunched Ghidra, Apple showed a prompt and I allowed both dynamic libraries to run by going to System Settings > Privacy and Security and allowing access.

**Desktop (please complete the following information):**
 - OS: Apple Silicon Mac OS
 - Version Sonoma 14.6.1

**Comment by sei-eschwartz** [comment]
https://github.com/CERTCC/kaiju/blob/main/.github/workflows/release_on_tag.yml#L71

There is no arm version for mac included in our releases.

**Comment by sei-eschwartz** [comment]
This should be fixed in release 241204.  Please try it out and make sure that it works for you.
